plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jvm-test-suite'
    id 'jacoco'
    id 'com.google.protobuf' version "0.10.0"
    id 'org.sonarqube' version '7.3.1.8318'
    id 'com.adarshr.test-logger' version '4.0.0'
    id 'com.diffplug.spotless' version '8.8.0'
    id 'com.autonomousapps.dependency-analysis' version '3.16.0'
}

group = 'com.minispring'
version = '0.0.1-SNAPSHOT'
description = 'auth-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

bootJar {
    archiveFileName = 'app.jar'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'
    implementation 'io.github.resilience4j:resilience4j-spring-boot4:2.4.0'
    implementation 'org.springframework.grpc:spring-grpc-server-spring-boot-starter:1.0.3'
    implementation 'com.google.protobuf:protobuf-java:4.35.0'
    implementation 'com.google.protobuf:protobuf-java-util:4.35.0'
    implementation 'org.keycloak:keycloak-admin-client:26.0.9'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    compileOnly 'org.projectlombok:lombok'
    compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation platform('org.instancio:instancio-bom:6.0.0-RC2')
    testImplementation 'org.instancio:instancio-core'
    testImplementation 'org.instancio:instancio-junit'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.testcontainers:junit-jupiter:1.19.7'
    testImplementation 'com.github.dasniko:testcontainers-keycloak:4.2.1'
    testImplementation 'org.testcontainers:testcontainers-postgresql:2.0.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

testing {
    suites {
        test(JvmTestSuite) {
            useJUnitJupiter()
        }

        integrationTest(JvmTestSuite) {
            dependencies {
                implementation project()
            }
            targets {
                configureEach {
                    testTask.configure {
                        shouldRunAfter(test)
                        systemProperty "spring.profiles.active", "test"
                        minHeapSize = "512m"
                        maxHeapSize = "2048m"
                    }
                }
            }
        }
    }
}

configurations {
    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
    integrationTestCompileOnly.extendsFrom testCompileOnly
    integrationTestAnnotationProcessor.extendsFrom testAnnotationProcessor
}

jacoco {
    toolVersion = "0.8.15"
}

tasks.named('jacocoTestReport') {
    dependsOn tasks.named('test'), tasks.named('integrationTest')

    reports {
        xml.required = true
        html.required = true
    }

    executionData.setFrom(fileTree(layout.buildDirectory).include("/jacoco/*.exec"))

    classDirectories.setFrom(
            files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                        "**/dto/**",
                        "**/config/**",
                        "**/mapper/**",
                        "**/exception/**",
                        "**/*Application.class"
                ])
            })
    )
}

sonar {
    properties {
        property "sonar.projectName", "User Service"
        property "sonar.host.url", System.getenv("SONAR_HOST_URL")
        property "sonar.token", System.getenv("SONAR_TOKEN")
        property "sonar.organization", System.getenv("SONAR_ORGANIZATION")
        property "sonar.projectKey", System.getenv("SONAR_PROJECT_KEY")
        property "sonar.coverage.jacoco.xmlReportPaths", "${layout.buildDirectory.get()}/reports/jacoco/test/jacocoTestReport.xml"
        property "sonar.junit.reportPaths", "${layout.buildDirectory.get()}/test-results/test,${layout.buildDirectory.get()}/test-results/integrationTest"
        property "sonar.coverage.exclusions", "**/dto/**, **/config/**, **/mapper/**, **/exception/**, **/*Application.java"
        property "sonar.qualitygate.wait", "true"
    }
}

dependencyAnalysis {
    issues {
        all {
            onAny {
                severity("warn")
            }
            onUnusedDependencies {
                exclude("org.springframework.boot:spring-boot-starter-*")
                exclude("org.projectlombok:lombok")
                exclude("org.mapstruct:*")
                exclude("me.paulschwarz:spring-dotenv")
            }
        }
    }
}

spotless {
    java {
        palantirJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
        targetExclude("**/build/generated/**/*")
    }
}

testlogger {
    theme = 'mocha'
    showStandardStreams = false
    showPassedStandardStreams = false
    showFailedStandardStreams = true
    slowThreshold = 2000
    showSummary = true
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.35.0"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.81.0"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc {}
            }
        }
    }
}
