services:

  keycloak-postgres:
    container_name: keycloak_postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_ROOT_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      AUTH_DB_USER: ${AUTH_DB_USERNAME}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_DB_SCHEMA: ${AUTH_DB_SCHEMA}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - ./docker-init/init-keycloak-user.sh:/docker-entrypoint-initdb.d/init-keycloak-user.sh
      - keycloak_pg_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${AUTH_DB_ROOT_USER}", "-d", "${AUTH_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "max_connections=50", "-c", "shared_buffers=256MB" ]

  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    container_name: keycloak
    command: start-dev --import-realm
    env_file:
      - '.env'
    environment:
      KC_HTTP_PORT: ${KC_HTTP_PORT}
      KC_DB: ${KC_DB}
      KC_DB_URL: ${AUTH_DB_URL}
      KC_DB_USERNAME: ${AUTH_DB_USERNAME}
      KC_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB_POOL_INITIAL_SIZE: ${KC_DB_POOL_INITIAL_SIZE}
      KC_DB_POOL_MIN_SIZE: ${KC_DB_POOL_MIN_SIZE}
      KC_DB_POOL_MAX_SIZE: ${KC_DB_POOL_MAX_SIZE}
      KC_TRANSACTION_XA_ENABLED: ${KC_TRANSACTION_XA_ENABLED}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_FEATURES: ${KC_FEATURES}
      JAVA_OPTS_APPEND: "-Xms512m -Xmx1024m -Dkeycloak.migration.replace-placeholders=true"
    ports:
      - "${KC_EXTERNAL_PORT}:${KC_HTTP_PORT}"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      keycloak-postgres:
        condition: service_healthy

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
      - "${GRPC_SERVER_PORT}:9090"
    env_file:
      - '.env'
    environment:
      SERVER_PORT: ${AUTH_SERVICE_PORT}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
    depends_on:
      - keycloak

networks:
  default:
    name: innowise-network

volumes:
  keycloak_pg_data: