spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: ${GRPC_SERVER_PORT}
      reflection:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/dev/protocol/openid-connect/certs
keycloak:
  auth-server-url: ${APP_AUTH_SERVER_URL}
  base-url: ${APP_BASE_URL}
  realm: ${APP_REALM}
  client-id: ${APP_CLIENT_ID}
  client-secret: ${APP_CLIENT_SECRET}