#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $AUTH_DB_USER WITH PASSWORD '$AUTH_DB_PASSWORD';

        GRANT CONNECT, CREATE ON DATABASE $POSTGRES_DB TO $AUTH_DB_USER;

        CREATE SCHEMA IF NOT EXISTS $AUTH_DB_SCHEMA;

        GRANT USAGE, CREATE ON SCHEMA $AUTH_DB_SCHEMA TO $AUTH_DB_USER;

        ALTER USER $AUTH_DB_USER SET search_path TO $AUTH_DB_SCHEMA;

        ALTER DEFAULT PRIVILEGES IN SCHEMA $AUTH_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO $AUTH_DB_USER;

        ALTER DEFAULT PRIVILEGES IN SCHEMA $AUTH_DB_SCHEMA GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $AUTH_DB_USER;
EOSQL